### ISSUE TITLE
AI Girl - Screenshot upsampling memory leak?

### ISSUE THREAD

**Issue by aGKamui** [IllusionMods/BepisPlugins#102] opened 2020-03-28 19:20 UTC
## Before submitting
- Update to latest BepisPlugins and supported version of BepInEx.
- Update your game to latest version.
- Make sure no other plugins are crashing or having issues (remove them for testing and see if your issue is fixed.)

**Describe the bug**
Running AI Girl, the studio I wanted to do several renders of the characters with alpha.
F11 did a few before the entire computer crashed, same thing happened when it rebooted and was doing the same thing, so pinpointed to that, started testing it and it looks like everytime I do a render it hogs the memory until I reset the scene.

**To Reproduce**
1. Go to Studio
2. Add a Character
2. F1 - set upsampling ratio to 4
4. Screenshot, check if it is already done in the cap folder
5. Keep doing it with task manager open and you'll see you keep having less available RAM do it a time too many your entire PC shuts down.

**Expected behavior**
Not shut down anyone's PC XD

**Comment by aGKamui** [comment] 2020-03-28 19:28
After testing it more, ALT-Tabbing, changing the value of the upsample to 1 then to 4 seems to be the deal breaker actually.

Because I tried it after booting up after having it set to 4 and the ram didn't go bonkers like it was.

**Comment by ShikiSuen** [comment] 2020-04-02 11:13
I didn't see any memory leak issue but I see the studio neo crashes everytime I set the upsampling > 1.

**Comment by ManlyMarco** [comment] 2020-04-02 17:26
Open your task manager and keep it on memory usage when trying to make the screenshot. Most likely you are running out of RAM with the higher upsampling setting since the usage raises exponentially.

**Comment by ShikiSuen** [comment] 2020-04-02 19:20
@ManlyMarco I have 32GB RAM (Mac Pro with double AMD FirePro D300).
The RAM usage of the Studio NEO never exceeds 6GB (in most times < 5GB).

**Comment by ManlyMarco** [comment] 2020-04-03 19:35
Can you send any logs you get when the crash happens? output log in game root and error logs in crash dump folders if any.

**Comment by ShikiSuen** [comment] 2020-04-05 00:24
@ManlyMarco Could you please tell me which directory are they located in?

**Comment by ShikiSuen** [comment] 2020-04-05 01:00
I temporarily bypassed this issue by running AI Shoujo on macOS Catalina instead of the phucking Windows 10. Now I can even extract 4096x2304 screenshots with 2x upsample.

Now here comes the new problem that the captured screenshots are in distorted alpha curve.

![image](https://user-images.githubusercontent.com/3164826/78464397-0edb4300-7724-11ea-8fac-479844f1e455.png)

**Comment by ShikiSuen** [comment] 2020-04-05 01:03
My previous reply talks about the issue happens when press F11.

By pressing F9 the gamma curve issue does not happen.

(I wonder why 3d models appear to be blurry while running on macOS. This is not an issue caused by BepisPlugins but I guess some hacks through these plugins may help solving this issue.)

P.S.: AI Shoujo is really GPU-consuming. The entire WindowServer of my macOS (similar to DWM on Windows) becomes sluggish and glitchy if I keep AI Shoujo running in the background.

**Comment by ManlyMarco** [comment] 2020-04-05 09:13
All log files and crash dumps are created in the game's root directory. 

I can't help much with issues on macOS since I don't have any mac machines (I'm pretty sure neither do other plugin devs).

Isn't the blur just the game's depth of field setting? Try taking a screenshot with no alpha/transparency and see what happens.

**Comment by ShikiSuen** [comment] 2020-04-05 14:12
@ManlyMarco There are no log files generated when the game crashes on Windows while taking upsampled screenshots. My assumption is that either AMD Windows drivers are badly written or AMD Crossfire technology is not supported by this game on Windows. It is likely that the Crossfire work combining my two AMD FirePro D300 graphic cards is done by macOS itself, and the game successfully recognizes the combined graphic card on macOS.

The in-game field depth blurring functions differently from how it behaves on Windows. I ended up turning it off. This field-depth-blurring malfunction does not affect with screenshots taken by F11 key with Bepis Screenshot Plugins installed & being functional.

**Comment by ShikiSuen** [comment] 2020-04-05 14:40
Looks like, among the problems I met now on macOS, the only one which happens on the plugins' side is the screenshot gamma curve issue I mentioned above.

**Comment by ShikiSuen** [comment] 2020-04-06 01:26
Previously I was testing with Japanese retail version of AI Shoujo.
Now I just tested this issue again with a pirated version of AI Shoujo and got this crash log:
[output_log.txt](https://github.com/IllusionMods/BepisPlugins/files/4435453/output_log.txt)

**Comment by ManlyMarco** [comment] 2020-04-06 13:12
The errors suggest a GPU driver or system issue, and less often corrupted game files or a hardware issue.

**Comment by ShikiSuen** [comment] 2020-04-08 14:36
I ended up buying a second-hand gaming desktop with GTX 1060, costing me over 70k JPY after tax.
(It is even 2x more expensive to consider eGPU solution for my Late-2013 Mac Pro.)

**Comment by ManlyMarco** [comment] 2020-04-08 15:02
Since the problem was caused by hardware/driver issues I'll close the issue.

**Closed by ManlyMarco** 2020-04-08 15:02 UTC
Labels: bug

**Comment by ShikiSuen** [comment] 2020-04-08 16:08
@ManlyMarco The reason is directly concerned with GPU.

My new gaming machine has only 8GB RAM (plus 3GB VRAM x 1 GTX 1060), and my Mac Pro has 32GB RAM (plus 2GB VRAM x 2 AMD FirePro D300).
